import sys
import time

def typewriter_effect(text, delay = 0.15):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print()

def main():
    typewriter_effect("Talking about...she met a king")
    typewriter_effect(".........")
    typewriter_effect("The Yellow King")
    typewriter_effect(".......")
    typewriter_effect("Which could be worse?....")
    typewriter_effect("To live as a villain....or die as a hero?")
    typewriter_effect("I say that.....I dont like people very much")
    typewriter_effect("And they pretty much don't like me")
    typewriter_effect(".......")
    typewriter_effect("AND SHE'S WONDERING WHY IM OT THERE")
    typewriter_effect("What a day hmm.....")
    typewriter_effect("Happy or sad?")
    typewriter_effect("Everybody is awful these days")
    typewriter_effect("You look lonely....I can fix that")
    typewriter_effect("I want.....a way out of loneliness")
    typewriter_effect("Do you like your job?")
    typewriter_effect("Not exactly")
    typewriter_effect("No music...")
    typewriter_effect("SO FORGIVE FOR NOT HAVING A GOOD NIGHT REST....")
    typewriter_effect("NOW WHY DONT YOU LOOKING FOR MY FUCKING DAUGHTER...")
    typewriter_effect("I'll break your heart...")
    typewriter_effect("Already broken")
    typewriter_effect("People keep asking me if im back")
    typewriter_effect("And I really dont have the answer")
    typewriter_effect("But now yeah....Im thinking Im back")
    typewriter_effect("Do you need friends?")
    typewriter_effect("I can be hard to live with...")
    typewriter_effect("Sometimes I just dont think im not good for people you know")
    typewriter_effect("January 3rd 1995.....My daughter's birthday")
    typewriter_effect("All hands in hands walk into extinction")
    typewriter_effect("I think human consiusness....is a tragic mistep of evolution")
    typewriter_effect("Rust Cohle")
    typewriter_effect("Giant gutter and outer space")
    typewriter_effect("We became to self aware")
    typewriter_effect("One last midnight")
    typewriter_effect("Brothers and sisters opting out of the raw deal")
    typewriter_effect("Whats the point of waking up in the morning?")
    typewriter_effect("I tell myself I bear witnesses but the real answer is...obviusly my program")
    typewriter_effect("......")
    typewriter_effect("What to say about life hmm?")
    typewriter_effect("The honorable thing for us as species to do is...deny our programming")
    typewriter_effect("Stop reproducing....")
    typewriter_effect("You had any sleep last night?")
    typewriter_effect("I dont sleep...I just dream")

if __name__ == "__main__":
    main()